### ISSUE TITLE
Fatal error detected

### ISSUE THREAD

**Issue by reazhossain** [Riifta/intelpy#1]
It was working fine, now Fatal error detected failed to execute script intelPy

**Comment by Riftr** [comment]
Pyinstaller makes it a bit hard to troubleshoot these errors so I am going to implement logging as part of the debug mode soon.

In the mean time, the simplest way to resolve this is to delete the C:\Users\ your username \AppData\Local\IntelPy\ folder and run the app again. You will need to set up your channels again however.

**Comment by reazhossain** [comment]
Thank you. deleting the files inside that folder worked for me

**Comment by reazhossain** [comment]
I have tried the new version, It keeps closing during start. Every time I reset the AppData files it works again.
