### ISSUE TITLE
Unable to open IntelPy.exe

### ISSUE THREAD

**Issue by Rastommy77** [Riifta/intelpy#4]
When I try to launch IntelPy.exe, it comes up with a blank windows for a second, than disappears.
The executable shows up in task manager but disappears as well.
This used to work fine yesterday and before, only change I've made was that I've started using a custom mp3 alarm.
I have rebooted the pc, same issue
Also deleted the files and unpacked them to a different location, same issue

**Comment by Riftr** [comment]
Hi, can you please try the new preview release at https://github.com/Riifta/intelpy/releases/tag/1.2b1 and let me know how you go. Please remove the current files and put the files that are in the Windows .zip in their place.

**Comment by Riftr** [comment]
Could you please try the new build at https://github.com/Riifta/intelpy/releases/tag/1.2b2 

When you run IntelPy, use the intelpydebug.bat file to run it. You will get a window with debug info and hopefully any crash information if it crashes. Hopefully this time it will run ok as it includes a few related bug fixes as well.

**Comment by kyelnick** [comment]
I began experiencing the same issues around the same time. I'm having the same problem with this new release. Here's the debug info: 
---- IntelPy ----
Debug enabled. See debug.log for output.
Archiving old logs (Windows)
Archive path file already existed, skipping
Archive path file already existed, skipping
Archive path file already existed, skipping
Archive path file already existed, skipping
Archive path file already existed, skipping
Archive path file already existed, skipping
Archive path file already existed, skipping
Archive path file already existed, skipping
Archive path file already existed, skipping
Archive path file already existed, skipping
Archive path file already existed, skipping
Archive path file already existed, skipping
Archive path file already existed, skipping
Archive path file already existed, skipping
Archive path file already existed, skipping
Archive path file already existed, skipping
Archive path file already existed, skipping
Archive path file already existed, skipping
Archive path file already existed, skipping
Archive path file already existed, skipping
Archive path file already existed, skipping
Archive path file already existed, skipping
Archive path file already existed, skipping
Archive path file already existed, skipping
Archive found 24 files.
Archive should have moved 0 files.
invalid load key, '\x00'.
Traceback (most recent call last):
  File "intelpy\eve\eveloghandler_worker.py", line 36, in run
  File "intelpy\eve\eveloghandler.py", line 35, in __init__
  File "intelpy\eve\eveloghandler.py", line 179, in unpickle_known_files
_pickle.UnpicklingError: invalid load key, '\x00'.


I'm unsure of where debug.log is located (didn't see it in the IntelPy director), but let me know if you need more info. Event Viewer is showing C:\Users\MYUSERNAME\AppData\Local\Temp\_MEI220722\Qt5Core.dll 
as the faulting module. I've deleted all temp files, but that didn't resolve the issue.

**Comment by kyelnick** [comment]
I deleted the files from: C:\Users\MYUSERNAME\AppData\Local\IntelPy     and this resolved my problem. 

Debug looked like this:
---- IntelPy ----
Debug enabled. See debug.log for output.
Archiving old logs (Windows)
Archive path file already existed, skipping
Archive path file already existed, skipping
Archive path file already existed, skipping
Archive path file already existed, skipping
Archive path file already existed, skipping
Archive path file already existed, skipping
Archive path file already existed, skipping
Archive path file already existed, skipping
Archive path file already existed, skipping
Archive path file already existed, skipping
Archive path file already existed, skipping
Archive path file already existed, skipping
Archive path file already existed, skipping
Archive path file already existed, skipping
Archive path file already existed, skipping
Archive path file already existed, skipping
Archive path file already existed, skipping
Archive path file already existed, skipping
Archive path file already existed, skipping
Archive path file already existed, skipping
Archive path file already existed, skipping
Archive path file already existed, skipping
Archive path file already existed, skipping
Archive path file already existed, skipping
Archive found 25 files.
Archive should have moved 1 files.

**Comment by Riftr** [comment]
Thanks, looks like that identified the bug. IntelPy stores its settings in your %appdata% folder under Local\IntelPy. One of those files stores the tracking history for your logs to know what line we were up to (so we don't have to parse the entire file each time) but loading that file (known_files.p) ran into issues.

For now I've put a temporary fix in that will check when the file is corrupt and reset it. I'm hoping to move to another library to handle it better in a future release though.

**Comment by Riftr** [comment]
Please try the release from https://github.com/Riifta/intelpy/releases/tag/1.2b3 and please post logs if it crashes again :)

**Comment by Riftr** [comment]
Didn't get a response so closing issue. If the problem reoccurs please let me know.
