### ISSUE TITLE
Unable to adjust sound

### ISSUE THREAD

**Issue by phobostr** [Riifta/intelpy#9]
Hi. Very cool software, thank you for sharing.
Installed and ran it on Win 10, works perfectly indicating hostiles in my area.
Problem is I cannot change the volume.
Lowering app volume or system volume does not help.
Muting the volume also does not help.

![image](https://github.com/user-attachments/assets/8f9bbd4d-e431-4a65-a13b-901145e9fc9c)

**Comment by Riftr** [comment]
I only have Windows 11 here to test with and on that I can adjust the volume of IntelPy like you would expect.

The issue may have something to do with your drivers. I can't seem to find anything related to Qt 5 + sound issues on Windows 10.

**Comment by phobostr** [comment]
I will install the app once i do a fresh Win10 install. I am sure this will fix it. Thank you for the feedback. We can close this ticket.
